### ISSUE TITLE
Add node index file so we can include TF nodes

### ISSUE THREAD

**Issue by jdelrue** [threefoldtech/planetary_network#20]
The nodes should be in our repo instead of using the public list, that way we can use TF nodes and add other nodes on the fly. The node list can be fetched from github (using something like https://raw.githubusercontent.com/threefoldtech/planetary_network/main/nodelist as url)

**Comment by ken-de-moor** [comment]
Updated list:

https://github.com/threefoldtech/zos-config/pull/5/files

**Comment by LennertDefauw1** [comment]
Planetary network desktop app uses this list: 

https://raw.githubusercontent.com/threefoldtech/planetary_network/feature/config-rework/nodelist

(branch still has to be merged)
